// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'identity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<InitiatorStartResult> apiHandshakeInitiatorStart({
  required List<int> privateKey,
}) => RustLib.instance.api.crateApiApiHandshakeInitiatorStart(
  privateKey: privateKey,
);

Future<ResponderStartResult> apiHandshakeResponderStart({
  required List<int> privateKey,
  required List<int> msg1Bytes,
}) => RustLib.instance.api.crateApiApiHandshakeResponderStart(
  privateKey: privateKey,
  msg1Bytes: msg1Bytes,
);

Future<InitiatorFinishResult> apiHandshakeInitiatorFinish({
  required List<int> privateKey,
  required List<int> ephemeralSecretBytes,
  required List<int> msg1Bytes,
  required List<int> msg2Bytes,
}) => RustLib.instance.api.crateApiApiHandshakeInitiatorFinish(
  privateKey: privateKey,
  ephemeralSecretBytes: ephemeralSecretBytes,
  msg1Bytes: msg1Bytes,
  msg2Bytes: msg2Bytes,
);

Future<void> apiHandshakeResponderFinish({
  required List<int> peerStaticPubBytes,
  required List<int> expectedMsg3Hash,
  required List<int> msg3Bytes,
}) => RustLib.instance.api.crateApiApiHandshakeResponderFinish(
  peerStaticPubBytes: peerStaticPubBytes,
  expectedMsg3Hash: expectedMsg3Hash,
  msg3Bytes: msg3Bytes,
);

Future<Uint8List> apiGenerateStaticKeypair() =>
    RustLib.instance.api.crateApiApiGenerateStaticKeypair();

Future<Uint8List> apiGetPublicKey({required List<int> privateKey}) =>
    RustLib.instance.api.crateApiApiGetPublicKey(privateKey: privateKey);
