// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'identity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1628196599;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'spdrop_core',
        ioDirectory: 'core/rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiApiGenerateStaticKeypair();

  Future<Uint8List> crateApiApiGetPublicKey({required List<int> privateKey});

  Future<InitiatorFinishResult> crateApiApiHandshakeInitiatorFinish({
    required List<int> privateKey,
    required List<int> ephemeralSecretBytes,
    required List<int> msg1Bytes,
    required List<int> msg2Bytes,
  });

  Future<InitiatorStartResult> crateApiApiHandshakeInitiatorStart({
    required List<int> privateKey,
  });

  Future<void> crateApiApiHandshakeResponderFinish({
    required List<int> peerStaticPubBytes,
    required List<int> expectedMsg3Hash,
    required List<int> msg3Bytes,
  });

  Future<ResponderStartResult> crateApiApiHandshakeResponderStart({
    required List<int> privateKey,
    required List<int> msg1Bytes,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiApiGenerateStaticKeypair() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiGenerateStaticKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGenerateStaticKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "api_generate_static_keypair",
        argNames: [],
      );

  @override
  Future<Uint8List> crateApiApiGetPublicKey({required List<int> privateKey}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetPublicKeyConstMeta,
        argValues: [privateKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetPublicKeyConstMeta => const TaskConstMeta(
    debugName: "api_get_public_key",
    argNames: ["privateKey"],
  );

  @override
  Future<InitiatorFinishResult> crateApiApiHandshakeInitiatorFinish({
    required List<int> privateKey,
    required List<int> ephemeralSecretBytes,
    required List<int> msg1Bytes,
    required List<int> msg2Bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          sse_encode_list_prim_u_8_loose(ephemeralSecretBytes, serializer);
          sse_encode_list_prim_u_8_loose(msg1Bytes, serializer);
          sse_encode_list_prim_u_8_loose(msg2Bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_initiator_finish_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiHandshakeInitiatorFinishConstMeta,
        argValues: [privateKey, ephemeralSecretBytes, msg1Bytes, msg2Bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiHandshakeInitiatorFinishConstMeta =>
      const TaskConstMeta(
        debugName: "api_handshake_initiator_finish",
        argNames: [
          "privateKey",
          "ephemeralSecretBytes",
          "msg1Bytes",
          "msg2Bytes",
        ],
      );

  @override
  Future<InitiatorStartResult> crateApiApiHandshakeInitiatorStart({
    required List<int> privateKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_initiator_start_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiHandshakeInitiatorStartConstMeta,
        argValues: [privateKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiHandshakeInitiatorStartConstMeta =>
      const TaskConstMeta(
        debugName: "api_handshake_initiator_start",
        argNames: ["privateKey"],
      );

  @override
  Future<void> crateApiApiHandshakeResponderFinish({
    required List<int> peerStaticPubBytes,
    required List<int> expectedMsg3Hash,
    required List<int> msg3Bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(peerStaticPubBytes, serializer);
          sse_encode_list_prim_u_8_loose(expectedMsg3Hash, serializer);
          sse_encode_list_prim_u_8_loose(msg3Bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiHandshakeResponderFinishConstMeta,
        argValues: [peerStaticPubBytes, expectedMsg3Hash, msg3Bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiHandshakeResponderFinishConstMeta =>
      const TaskConstMeta(
        debugName: "api_handshake_responder_finish",
        argNames: ["peerStaticPubBytes", "expectedMsg3Hash", "msg3Bytes"],
      );

  @override
  Future<ResponderStartResult> crateApiApiHandshakeResponderStart({
    required List<int> privateKey,
    required List<int> msg1Bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          sse_encode_list_prim_u_8_loose(msg1Bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_responder_start_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiHandshakeResponderStartConstMeta,
        argValues: [privateKey, msg1Bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiHandshakeResponderStartConstMeta =>
      const TaskConstMeta(
        debugName: "api_handshake_responder_start",
        argNames: ["privateKey", "msg1Bytes"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  InitiatorFinishResult dco_decode_initiator_finish_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return InitiatorFinishResult(
      msg3Bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      peerStaticPub: dco_decode_list_prim_u_8_strict(arr[1]),
      sas: dco_decode_String(arr[2]),
      sessionKeyRx: dco_decode_list_prim_u_8_strict(arr[3]),
      sessionKeyTx: dco_decode_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  InitiatorStartResult dco_decode_initiator_start_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InitiatorStartResult(
      msg1Bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      ephemeralSecret: dco_decode_list_prim_u_8_strict(arr[1]),
      initiatorNonce: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ResponderStartResult dco_decode_responder_start_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ResponderStartResult(
      msg2Bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      peerStaticPub: dco_decode_list_prim_u_8_strict(arr[1]),
      expectedMsg3Hash: dco_decode_list_prim_u_8_strict(arr[2]),
      sas: dco_decode_String(arr[3]),
      sessionKeyRx: dco_decode_list_prim_u_8_strict(arr[4]),
      sessionKeyTx: dco_decode_list_prim_u_8_strict(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  InitiatorFinishResult sse_decode_initiator_finish_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msg3Bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_peerStaticPub = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sas = sse_decode_String(deserializer);
    var var_sessionKeyRx = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sessionKeyTx = sse_decode_list_prim_u_8_strict(deserializer);
    return InitiatorFinishResult(
      msg3Bytes: var_msg3Bytes,
      peerStaticPub: var_peerStaticPub,
      sas: var_sas,
      sessionKeyRx: var_sessionKeyRx,
      sessionKeyTx: var_sessionKeyTx,
    );
  }

  @protected
  InitiatorStartResult sse_decode_initiator_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msg1Bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_ephemeralSecret = sse_decode_list_prim_u_8_strict(deserializer);
    var var_initiatorNonce = sse_decode_list_prim_u_8_strict(deserializer);
    return InitiatorStartResult(
      msg1Bytes: var_msg1Bytes,
      ephemeralSecret: var_ephemeralSecret,
      initiatorNonce: var_initiatorNonce,
    );
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ResponderStartResult sse_decode_responder_start_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_msg2Bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_peerStaticPub = sse_decode_list_prim_u_8_strict(deserializer);
    var var_expectedMsg3Hash = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sas = sse_decode_String(deserializer);
    var var_sessionKeyRx = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sessionKeyTx = sse_decode_list_prim_u_8_strict(deserializer);
    return ResponderStartResult(
      msg2Bytes: var_msg2Bytes,
      peerStaticPub: var_peerStaticPub,
      expectedMsg3Hash: var_expectedMsg3Hash,
      sas: var_sas,
      sessionKeyRx: var_sessionKeyRx,
      sessionKeyTx: var_sessionKeyTx,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_initiator_finish_result(
    InitiatorFinishResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.msg3Bytes, serializer);
    sse_encode_list_prim_u_8_strict(self.peerStaticPub, serializer);
    sse_encode_String(self.sas, serializer);
    sse_encode_list_prim_u_8_strict(self.sessionKeyRx, serializer);
    sse_encode_list_prim_u_8_strict(self.sessionKeyTx, serializer);
  }

  @protected
  void sse_encode_initiator_start_result(
    InitiatorStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.msg1Bytes, serializer);
    sse_encode_list_prim_u_8_strict(self.ephemeralSecret, serializer);
    sse_encode_list_prim_u_8_strict(self.initiatorNonce, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_responder_start_result(
    ResponderStartResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.msg2Bytes, serializer);
    sse_encode_list_prim_u_8_strict(self.peerStaticPub, serializer);
    sse_encode_list_prim_u_8_strict(self.expectedMsg3Hash, serializer);
    sse_encode_String(self.sas, serializer);
    sse_encode_list_prim_u_8_strict(self.sessionKeyRx, serializer);
    sse_encode_list_prim_u_8_strict(self.sessionKeyTx, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
