// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class InitiatorFinishResult {
  final Uint8List msg3Bytes;
  final Uint8List peerStaticPub;
  final String sas;
  final Uint8List sessionKeyRx;
  final Uint8List sessionKeyTx;

  const InitiatorFinishResult({
    required this.msg3Bytes,
    required this.peerStaticPub,
    required this.sas,
    required this.sessionKeyRx,
    required this.sessionKeyTx,
  });

  @override
  int get hashCode =>
      msg3Bytes.hashCode ^
      peerStaticPub.hashCode ^
      sas.hashCode ^
      sessionKeyRx.hashCode ^
      sessionKeyTx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitiatorFinishResult &&
          runtimeType == other.runtimeType &&
          msg3Bytes == other.msg3Bytes &&
          peerStaticPub == other.peerStaticPub &&
          sas == other.sas &&
          sessionKeyRx == other.sessionKeyRx &&
          sessionKeyTx == other.sessionKeyTx;
}

class InitiatorStartResult {
  final Uint8List msg1Bytes;
  final Uint8List ephemeralSecret;
  final Uint8List initiatorNonce;

  const InitiatorStartResult({
    required this.msg1Bytes,
    required this.ephemeralSecret,
    required this.initiatorNonce,
  });

  @override
  int get hashCode =>
      msg1Bytes.hashCode ^ ephemeralSecret.hashCode ^ initiatorNonce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InitiatorStartResult &&
          runtimeType == other.runtimeType &&
          msg1Bytes == other.msg1Bytes &&
          ephemeralSecret == other.ephemeralSecret &&
          initiatorNonce == other.initiatorNonce;
}

class ResponderStartResult {
  final Uint8List msg2Bytes;
  final Uint8List peerStaticPub;
  final Uint8List expectedMsg3Hash;
  final String sas;
  final Uint8List sessionKeyRx;
  final Uint8List sessionKeyTx;

  const ResponderStartResult({
    required this.msg2Bytes,
    required this.peerStaticPub,
    required this.expectedMsg3Hash,
    required this.sas,
    required this.sessionKeyRx,
    required this.sessionKeyTx,
  });

  @override
  int get hashCode =>
      msg2Bytes.hashCode ^
      peerStaticPub.hashCode ^
      expectedMsg3Hash.hashCode ^
      sas.hashCode ^
      sessionKeyRx.hashCode ^
      sessionKeyTx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResponderStartResult &&
          runtimeType == other.runtimeType &&
          msg2Bytes == other.msg2Bytes &&
          peerStaticPub == other.peerStaticPub &&
          expectedMsg3Hash == other.expectedMsg3Hash &&
          sas == other.sas &&
          sessionKeyRx == other.sessionKeyRx &&
          sessionKeyTx == other.sessionKeyTx;
}
